package com.example.model

enum class SandboxCategory(val displayName: String, val icon: String) {
    ALL("All Items", "⭐"),
    BUILDING("Building", "🧱"),
    TOOLS_COMBAT("Gear & Combat", "⚔️"),
    REDSTONE("Redstone", "🔴"),
    FOOD_MAGIC("Food & Alchemy", "🧪"),
    MATERIALS("Materials", "💎")
}

data class SandboxItem(
    val id: String,
    val name: String,
    val category: SandboxCategory,
    val isBlock: Boolean = false
)

object SandboxDatabase {

    val ITEMS: List<SandboxItem> = listOf(
        // Building Blocks
        SandboxItem("oak_planks", "Oak Planks", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("oak_log", "Oak Log", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("cobblestone", "Cobblestone", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("stone", "Stone", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("smooth_stone", "Smooth Stone", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("sand", "Sand", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("glass", "Glass", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("obsidian", "Obsidian", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("crafting_table", "Crafting Table", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("furnace", "Furnace", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("blast_furnace", "Blast Furnace", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("smoker", "Smoker", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("chest", "Chest", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("trapped_chest", "Trapped Chest", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("barrel", "Barrel", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("ender_chest", "Ender Chest", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("shulker_box", "Shulker Box", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("bookshelf", "Bookshelf", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("anvil", "Anvil", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("torch", "Torch", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("soul_torch", "Soul Torch", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("campfire", "Campfire", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("lantern", "Lantern", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("ladder", "Ladder", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("scaffolding", "Scaffolding", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("oak_door", "Oak Door", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("iron_door", "Iron Door", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("oak_trapdoor", "Oak Trapdoor", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("iron_trapdoor", "Iron Trapdoor", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("oak_fence", "Oak Fence", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("oak_fence_gate", "Oak Fence Gate", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("tnt", "TNT", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("bed", "Red Bed", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("note_block", "Note Block", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("jukebox", "Jukebox", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("loom", "Loom", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("cartography_table", "Cartography Table", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("fletching_table", "Fletching Table", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("smithing_table", "Smithing Table", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("grindstone", "Grindstone", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("stonecutter", "Stonecutter", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("glass_pane", "Glass Pane", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("iron_bars", "Iron Bars", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("redstone_block", "Block of Redstone", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("iron_block", "Block of Iron", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("gold_block", "Block of Gold", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("diamond_block", "Block of Diamond", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("netherite_block", "Block of Netherite", SandboxCategory.BUILDING, isBlock = true),
        SandboxItem("hay_bale", "Hay Bale", SandboxCategory.BUILDING, isBlock = true),

        // Tools & Combat
        SandboxItem("netherite_sword", "Netherite Sword", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("diamond_sword", "Diamond Sword", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("golden_sword", "Golden Sword", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("iron_sword", "Iron Sword", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("stone_sword", "Stone Sword", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("wooden_sword", "Wooden Sword", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("netherite_pickaxe", "Netherite Pickaxe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("diamond_pickaxe", "Diamond Pickaxe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("golden_pickaxe", "Golden Pickaxe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("iron_pickaxe", "Iron Pickaxe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("stone_pickaxe", "Stone Pickaxe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("wooden_pickaxe", "Wooden Pickaxe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("netherite_axe", "Netherite Axe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("diamond_axe", "Diamond Axe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("iron_axe", "Iron Axe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("stone_axe", "Stone Axe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("wooden_axe", "Wooden Axe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("netherite_shovel", "Netherite Shovel", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("diamond_shovel", "Diamond Shovel", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("iron_shovel", "Iron Shovel", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("wooden_shovel", "Wooden Shovel", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("netherite_hoe", "Netherite Hoe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("diamond_hoe", "Diamond Hoe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("iron_hoe", "Iron Hoe", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("bow", "Bow", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("crossbow", "Crossbow", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("arrow", "Arrow", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("spectral_arrow", "Spectral Arrow", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("shield", "Shield", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("shears", "Shears", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("flint_and_steel", "Flint and Steel", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("fishing_rod", "Fishing Rod", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("bucket", "Bucket", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("water_bucket", "Water Bucket", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("lava_bucket", "Lava Bucket", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("clock", "Clock", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("compass", "Compass", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("spyglass", "Spyglass", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("lead", "Lead", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("name_tag", "Name Tag", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("diamond_helmet", "Diamond Helmet", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("diamond_chestplate", "Diamond Chestplate", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("diamond_leggings", "Diamond Leggings", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("diamond_boots", "Diamond Boots", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("iron_helmet", "Iron Helmet", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("iron_chestplate", "Iron Chestplate", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("iron_leggings", "Iron Leggings", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("iron_boots", "Iron Boots", SandboxCategory.TOOLS_COMBAT),
        SandboxItem("turtle_helmet", "Turtle Helmet", SandboxCategory.TOOLS_COMBAT),

        // Redstone & Transport
        SandboxItem("redstone", "Redstone Dust", SandboxCategory.REDSTONE),
        SandboxItem("redstone_torch", "Redstone Torch", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("redstone_repeater", "Redstone Repeater", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("redstone_comparator", "Redstone Comparator", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("piston", "Piston", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("sticky_piston", "Sticky Piston", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("dispenser", "Dispenser", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("dropper", "Dropper", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("hopper", "Hopper", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("observer", "Observer", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("lever", "Lever", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("stone_button", "Stone Button", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("oak_button", "Oak Button", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("stone_pressure_plate", "Stone Pressure Plate", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("oak_pressure_plate", "Oak Pressure Plate", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("tripwire_hook", "Tripwire Hook", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("target", "Target", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("daylight_detector", "Daylight Detector", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("minecart", "Minecart", SandboxCategory.REDSTONE),
        SandboxItem("rail", "Rail", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("powered_rail", "Powered Rail", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("detector_rail", "Detector Rail", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("activator_rail", "Activator Rail", SandboxCategory.REDSTONE, isBlock = true),
        SandboxItem("oak_boat", "Oak Boat", SandboxCategory.REDSTONE),

        // Food & Magic
        SandboxItem("apple", "Apple", SandboxCategory.FOOD_MAGIC),
        SandboxItem("golden_apple", "Golden Apple", SandboxCategory.FOOD_MAGIC),
        SandboxItem("golden_carrot", "Golden Carrot", SandboxCategory.FOOD_MAGIC),
        SandboxItem("bread", "Bread", SandboxCategory.FOOD_MAGIC),
        SandboxItem("cookie", "Cookie", SandboxCategory.FOOD_MAGIC),
        SandboxItem("cake", "Cake", SandboxCategory.FOOD_MAGIC, isBlock = true),
        SandboxItem("pumpkin_pie", "Pumpkin Pie", SandboxCategory.FOOD_MAGIC),
        SandboxItem("mushroom_stew", "Mushroom Stew", SandboxCategory.FOOD_MAGIC),
        SandboxItem("honey_bottle", "Honey Bottle", SandboxCategory.FOOD_MAGIC),
        SandboxItem("brewing_stand", "Brewing Stand", SandboxCategory.FOOD_MAGIC, isBlock = true),
        SandboxItem("cauldron", "Cauldron", SandboxCategory.FOOD_MAGIC, isBlock = true),
        SandboxItem("glass_bottle", "Glass Bottle", SandboxCategory.FOOD_MAGIC),
        SandboxItem("enchanting_table", "Enchanting Table", SandboxCategory.FOOD_MAGIC, isBlock = true),
        SandboxItem("beacon", "Beacon", SandboxCategory.FOOD_MAGIC, isBlock = true),
        SandboxItem("conduit", "Conduit", SandboxCategory.FOOD_MAGIC, isBlock = true),
        SandboxItem("end_crystal", "End Crystal", SandboxCategory.FOOD_MAGIC),
        SandboxItem("eye_of_ender", "Eye of Ender", SandboxCategory.FOOD_MAGIC),
        SandboxItem("ender_pearl", "Ender Pearl", SandboxCategory.FOOD_MAGIC),
        SandboxItem("blaze_rod", "Blaze Rod", SandboxCategory.FOOD_MAGIC),
        SandboxItem("blaze_powder", "Blaze Powder", SandboxCategory.FOOD_MAGIC),
        SandboxItem("magma_cream", "Magma Cream", SandboxCategory.FOOD_MAGIC),
        SandboxItem("fermented_spider_eye", "Fermented Spider Eye", SandboxCategory.FOOD_MAGIC),
        SandboxItem("fire_charge", "Fire Charge", SandboxCategory.FOOD_MAGIC),

        // Materials
        SandboxItem("diamond", "Diamond", SandboxCategory.MATERIALS),
        SandboxItem("gold_ingot", "Gold Ingot", SandboxCategory.MATERIALS),
        SandboxItem("iron_ingot", "Iron Ingot", SandboxCategory.MATERIALS),
        SandboxItem("coal", "Coal", SandboxCategory.MATERIALS),
        SandboxItem("charcoal", "Charcoal", SandboxCategory.MATERIALS),
        SandboxItem("stick", "Stick", SandboxCategory.MATERIALS),
        SandboxItem("string", "String", SandboxCategory.MATERIALS),
        SandboxItem("feather", "Feather", SandboxCategory.MATERIALS),
        SandboxItem("gunpowder", "Gunpowder", SandboxCategory.MATERIALS),
        SandboxItem("flint", "Flint", SandboxCategory.MATERIALS),
        SandboxItem("leather", "Leather", SandboxCategory.MATERIALS),
        SandboxItem("paper", "Paper", SandboxCategory.MATERIALS),
        SandboxItem("book", "Book", SandboxCategory.MATERIALS),
        SandboxItem("slimeball", "Slimeball", SandboxCategory.MATERIALS),
        SandboxItem("quartz", "Nether Quartz", SandboxCategory.MATERIALS),
        SandboxItem("wheat", "Wheat", SandboxCategory.MATERIALS),
        SandboxItem("sugar", "Sugar", SandboxCategory.MATERIALS),
        SandboxItem("egg", "Egg", SandboxCategory.MATERIALS),
        SandboxItem("bowl", "Bowl", SandboxCategory.MATERIALS),
        SandboxItem("bone", "Bone", SandboxCategory.MATERIALS),
        SandboxItem("glowstone_dust", "Glowstone Dust", SandboxCategory.MATERIALS),
        SandboxItem("amethyst_shard", "Amethyst Shard", SandboxCategory.MATERIALS)
    )

    private val itemMap = ITEMS.associateBy { it.id }

    fun findItem(id: String): SandboxItem? = itemMap[id]

    fun isBlockItem(id: String): Boolean = itemMap[id]?.isBlock ?: false
}
